name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  make_release:
    runs-on: self-hosted
    steps:
      - name: Calc version and push tag
        id: calc_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          fetch_all_tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: ""

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          fetch_all_tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: release-drafter/release-drafter@master
        with:
          name: ${{ steps.calc_version.outputs.new_tag }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          publish: ${{ ((github.head_ref || github.ref_name) == 'develop') || ((github.head_ref || github.ref_name) == 'master') }}
          prerelease: ${{ (github.head_ref || github.ref_name) != 'master' }}
          draft: ${{ github.ref_name != 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
