name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  make_release:
    runs-on: self-hosted
    steps:
      - name: Calc tag
        id: calc_tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          fetch_all_tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: "v"

      - name: Generate versions
        id: generate_versions
        run: |
          TAGSAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | cut -c 1-100)
          echo "latest_version=${TAGSAFE_BRANCH_NAME}-latest" >> $GITHUB_OUTPUT

          LATEST_TAG=${{steps.calc_tag_version.outputs.new_version}}
          LATEST_VERSION=v$LATEST_TAG
          SHORT_SHA=$(git rev-parse --short "${{ github.sha }}")
          NEW_VERSION="d$LATEST_TAG-$SHORT_SHA"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "new_version=$NEW_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_STEP_SUMMARY
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.generate_versions.outputs.new_version }}
          tag_prefix: ""

      - uses: release-drafter/release-drafter@master
        with:
          name: ${{ steps.calc_tag_version.outputs.new_version }}
          tag: ${{ steps.generate_versions.outputs.latest_version }}
          publish: ${{ ((github.head_ref || github.ref_name) == 'develop') || ((github.head_ref || github.ref_name) == 'master') }}
          prerelease: ${{ (github.head_ref || github.ref_name) != 'master' }}
          draft: ${{ github.ref_name != 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
